const words = {
    "apple": "a round fruit with red or green skin and a whitish inside",
    "book": "a written or printed work consisting of pages glued or sewn together along one side and bound in covers.",
    "cat": "a small domesticated carnivorous mammal with soft fur, a short snout, and retractable claws.",
    "dog": "a domesticated carnivorous mammal that typically has a long snout, an acute sense of smell, and a barking, howling, or whining voice.",
    "house": "a building for human habitation, especially one that is lived in by a family or small group of people.",
    "computer": "an electronic device for storing and processing data, typically in binary form, according to instructions given to it in a variable program.",
    "keyboard": "a panel of keys that operate a computer or typewriter.",
    "mouse": "a hand-held pointing device that detects two-dimensional motion relative to a surface.",
    "monitor": "a screen which displays an image generated by a computer.",
    "software": "the programs and other operating information used by a computer.",
    "hardware": "the physical parts of a computer system.",
    "internet": "a global computer network providing a variety of information and communication facilities, consisting of interconnected networks using standardized communication protocols.",
    "email": "messages distributed by electronic means from one computer user to one or more recipients via a network.",
    "code": "a system of words, letters, figures, or other symbols substituted for other words, letters, etc., especially for the purposes of secrecy.",
    "programming": "the process of writing computer programs.",
    "language": "the method of human communication, either spoken or written, consisting of the use of words in a structured and conventional way.",
    "developer": "a person who creates computer software.",
    "design": "a plan or drawing produced to show the look and function or workings of a building, garment, or other object before it is built or made.",
    "interface": "a point where two systems, subjects, organizations, etc., meet and interact.",
    "application": "a program or piece of software designed and written to fulfill a particular purpose of the user."
};

let currentWord = "";

function getRandomWord() {
    const wordKeys = Object.keys(words);
    const randomIndex = Math.floor(Math.random() * wordKeys.length);
    return wordKeys[randomIndex];
}

function displayWord() {
    currentWord = getRandomWord();
    document.getElementById("word-container").textContent = currentWord;
}

function checkAnswer() {
    const userAnswer = document.getElementById("answer-input").value.toLowerCase();
    const correctAnswer = words[currentWord].toLowerCase();
    const resultContainer = document.getElementById("result-container");

    if (userAnswer === correctAnswer) {
        resultContainer.textContent = "Correct!";
        resultContainer.style.color = "#2ecc71";
    } else {
        resultContainer.textContent = `Incorrect. The correct answer is: ${words[currentWord]}`;
        resultContainer.style.color = "#e74c3c";
    }
}

document.getElementById("check-btn").addEventListener("click", checkAnswer);
document.getElementById("next-btn").addEventListener("click", () => {
    displayWord();
    document.getElementById("answer-input").value = "";
    document.getElementById("result-container").textContent = "";
});

window.onload = displayWord;
